#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-svnkit
Version  : 1.8.5
Release  : 1
URL      : https://repo1.maven.org/maven2/org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.jar
Source0  : https://repo1.maven.org/maven2/org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.jar
Source1  : https://repo1.maven.org/maven2/org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : TMate
Requires: mvn-svnkit-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-svnkit package.
Group: Data

%description data
data components for the mvn-svnkit package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/tmatesoft/svnkit/svnkit/1.8.5
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/tmatesoft/svnkit/svnkit/1.8.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/tmatesoft/svnkit/svnkit/1.8.5
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/tmatesoft/svnkit/svnkit/1.8.5


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.jar
/usr/share/java/.m2/repository/org/tmatesoft/svnkit/svnkit/1.8.5/svnkit-1.8.5.pom
